
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ 主连接端口
      - "15672:15672" # RabbitMQ 管理控制台端口
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - luna_service_net

networks:
  luna_service_net:
    name: luna_service_net
